MCUX-85253[RTT] Fix RTT debug console build error
 - Using SDK_DEBUGCONSOLE == DEBUGCONSOLE_DISABLE with
   RTT debug console will get errors like:

   mcuxsdk/middleware/wifi_nxp/incl/wlcmgr/wlan.h:5143:99:
   error: expected expression before ';' token
   (void)PRINTF("%02X:", mac[0]);

 - Change to use #define PRINTF(...) DbgConsole_Disabled()

Signed-off-by: Jason Yu <zejiang.yu@nxp.com>